search field padding
salim-lachdhaf/searchable_dropdown pull request #226
Opened 2021-08-02 19:33 UTC by vasilich6107

2021-08-02 19:33 UTC, vasilich6107 commented
@salim-lachdhaf you've merged one but got two more ;-)

2021-08-02 19:38 UTC, vasilich6107 commented
Fixed confilcts

2021-08-03 07:07 UTC, salim-lachdhaf requested changes
`searchFieldPadding` should be an attribute of `searchFieldProps`

2021-08-03 07:35 UTC, vasilich6107 commented
fixed

2021-08-09 17:06 UTC, salim-lachdhaf requested changes

2021-08-09 19:53 UTC, vasilich6107 commented on lib/src/text_field_props.dart
>      this.dragStartBehavior = DragStartBehavior.start,
done

2021-08-11 12:06 UTC, merged